image:
  - Visual Studio 2015

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

install:
  - cmd: git submodule -q update --init
  
build_script:
  - ps: cd cpp
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -C "%CONFIG%" --output-on-failure